name: FTP Deploy

on:
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar para o deploy

jobs:
  deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Faz o checkout do código do repositório

    - name: Install lftp
      run: sudo apt-get install -y lftp  # Instala o cliente lftp no ambiente
    - name: Substitute secrets in PHP file
      run: 
        sed -i 's/{{DB_HOST}}/${{ secrets.DB_HOST }}/g' RestAPI/config.php
        sed -i 's/{{DB_USER}}/${{ secrets.DB_USER }}/g' RestAPI/config.php
        sed -i 's/{{DB_PASSWORD}}/${{ secrets.DB_PASSWORD }}/g' RestAPI/config.php

    - name: Trigger PHP Script via cURL
      run: 
       curl -X GET "http://criis-projects.inesctec.pt/pikachu/pikachuPM/git.php"


